name: shiny
channels:
  - conda-forge
  - defaults
dependencies:
  - shiny=1.1.0
  - python=3.11.0
  - plotly=5.24.1
  - pandas=2.2.2
  - pip=24.2
  - numpy=2.1.2
  - scipy=1.14.1
  - pip:
    - faicons==0.2.2
    - shinylive==0.6.0
    - shinywidgets==0.3.3
    - ridgeplot==0.1.30
    - pre-commit==4.0.1
